name: Upload to S3

on:
  push:
    branches:
      - main  # main ブランチに push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: AWS CLI セットアップ
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: S3に静的ファイルをアップロード
        run: |
          aws s3 sync ./app/html s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \